### PR TITLE
First draft of GATE 9 migration guide

### PR DESCRIPTION
**Pull request by acoussat**
As discussed with @dsarrut, this is a proposal for a section in the documentation in which the same GATE simulation is implemented both in GATE 9 and GATE 10. The goal is to collect such pairs of GATE simulation to help newcomers to GATE 10 translate their simulations. Of course this is just a draft, comments are obviously welcome.

### CODE REVIEW

**Comment by SimonRit** [comment]
Good idea! Maybe add a reference to the paper using this phantom https://doi.org/10.1118/1.4789589 and to https://github.com/SimonRit/PCT? And I would put the code used to calculate the translations instead of this table of translations. It was done in Matlab:
``` Matlab
sradius = 4;
radius = [0,1*sradius:sradius:100-sradius/2];

sangle = 139;
angles = [0:sangle:sangle*(length(radius)-1)];
size(angles)
angles = angles.*pi/180;
posx = radius.*cos(angles);
posy = radius.*sin(angles);
plot(posx,posy,'r*');
axis square;

fid=fopen('spiral.mac','w');
fprintf(fid, '# Mother of all\n');
fprintf(fid, '/gate/world/daughters/name              Spiral\n');
fprintf(fid, '/gate/world/daughters/insert            cylinder\n');
fprintf(fid, '/gate/Spiral/geometry/setRmin           0 cm\n');
fprintf(fid, '/gate/Spiral/geometry/setRmax           10 cm\n');
fprintf(fid, '/gate/Spiral/geometry/setHeight         40 cm\n');
fprintf(fid, '/gate/Spiral/setMaterial                Water\n');
fprintf(fid, '/gate/Spiral/vis/setColor               yellow\n');
fprintf(fid, '/gate/Spiral/vis/setVisible             1\n\n');

for i=1:length(radius)
    fprintf(fid, '# Insert at radius %.2f mm and angle %.2f degree\n', radius(i), angles(i)*180/pi);
    fprintf(fid, '/gate/Spiral/daughters/name             SpiralInsert%.02d\n', i);
    fprintf(fid, '/gate/Spiral/daughters/insert           cylinder\n');
    fprintf(fid, '/gate/SpiralInsert%.02d/geometry/setRmin         0 mm\n', i);
    fprintf(fid, '/gate/SpiralInsert%.02d/geometry/setRmax         1 mm\n', i);
    fprintf(fid, '/gate/SpiralInsert%.02d/geometry/setHeight       40 cm\n', i);
    fprintf(fid, '/gate/SpiralInsert%.02d/setMaterial              Aluminium\n', i);    
    fprintf(fid, '/gate/SpiralInsert%.02d/placement/setTranslation %.4f %.4f 0 mm\n', i, posx(i), posy(i))
    fprintf(fid, '/gate/SpiralInsert%.02d/vis/setColor             yellow\n', i);
    fprintf(fid, '/gate/SpiralInsert%.02d/vis/setVisible           1\n\n', i);
end
```

**Comment by tbaudier** [comment]
Maybe you can write on the same page https://opengate-python.readthedocs.io/en/master/user_guide/user_guide_how_to_convert_example_1.html

**Comment by BishopWolf** [comment]
> Maybe you can write on the same page https://opengate-python.readthedocs.io/en/master/user_guide/user_guide_how_to_convert_example_1.html


Please use two columns side by side in the examples. See this https://stackoverflow.com/questions/65340271/display-code-in-two-columns-in-restructured-text

**Comment by acoussat** [comment]
@SimonRit I have added the links as you suggested, thanks. Concerning the MATLAB code, I have converted it in Python in the GATE 10 simulation instead.
@tbaudier I moved my example below the one that was already present. The resulting page is ugly but I guess it's a first start.
@BishopWolf I would rather use RST's `list-table`s, as the format is much easier to write in my opinion. You can check the code in this PR for an example.

**Comment by dsarrut** [comment]
thanks you all !

**Pull request merged**
