### PR TITLE
Replace os by pathlib to avoid OS related errors and improve code maintenance

### PR DESCRIPTION
**Pull request by BishopWolf**
This PR fixes fresh installations errors when parent folders are not created by default giving 
```
FileNotFoundError: [Errno 2] No such file or directory: '...
```

These errors were triggered by some tests and are all solved by this PR. The change ensures the folders AND all their parents are created.

### CODE REVIEW

**Comment by dsarrut** [comment]
Excellent, thanks!

**Comment by BishopWolf** [comment]
> Excellent, thanks! However, I got: AttributeError: module 'os' has no attribute 'mkdirs' maybe makedirs ?

I have changed all os calls by pathlib. This is very easy to maintain as all OS related specificities are automatically handled

**Comment by BishopWolf** [comment]
For reference: https://www.freecodecamp.org/news/how-to-use-pathlib-module-in-python/

**Comment by BishopWolf** [comment]
I am solving all errors caught by the tests

**Comment by BishopWolf** [comment]
There are still places expecting string paths instead of path objects. As a rule, you can't pass strings to methods expecting paths, as it's very difficult to maintain. This is why pathlib is preferred.
Example:
```python
path1 = "/some/path"
path2 = "/some/path/"

# adding a file pathlib way
file1 = Path(path1) / "myfile"
file2 = Path(path2) / "myfile"

assert(file1.name == file2.name) # returns true

# os way
file1 = os.path.join(path1, "myfile")
file2 = os.path.join(path2, "myfile")

assert(file1== file2) # returns false
# file1 is "/some/path/myfile"
# file2 is ""/some/path//myfile"
```

**Comment by BishopWolf** [comment]
I see some merge conflicts with the last pull in wget. @tbaudier may you please review?

**Comment by BishopWolf** [comment]
@tbaudier : all tests are passing now

**Comment by BishopWolf** [comment]
@tbaudier : my tests didn't show any errors, see https://github.com/BishopWolf/opengate/actions/runs/10093731109/job/27911347164

Something is weird

**Comment by tbaudier** [comment]
> @tbaudier : my tests didn't show any errors, see https://github.com/BishopWolf/opengate/actions/runs/10093731109/job/27911347164
> 
> Something is weird

I will look at your PR, I think it's due to the rebasing of the branch. Do not modify it for the moment and I will try to do the necessary.
Thomas

**Comment by BishopWolf** [comment]
This error is because filename shall be Path:
```
 File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/opengate/engines.py", line 612, in stop_simulation
    actor.EndSimulationAction()
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/opengate/actors/miscactors.py", line 126, in EndSimulationAction
    self.write(self.user_info.output)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/opengate/actors/miscactors.py", line 146, in write
    with filename.open("w") as f:
         ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'open'
```

But it's being called by 
image

and user_info.output is just a filename string without path

**Pull request merged**
