### PR TITLE
Fix generic source life time

### PR DESCRIPTION
**Pull request by nkrah**
Fixes the bug described in issue #197 and addresses the problem indicated in PR #138.

### CODE REVIEW

**Comment by dsarrut** [comment]
See #226

**Comment by dsarrut** [comment]
Unsure : should we close this PR ? The half life issue is resolved in #226 (already merged) ?

**Comment by nkrah** [comment]
I’d say yes, let’s close it. If it’s resolved. There is also the issue opened by Hermann where I would put a reference to the merged PR and ask if the issue is resolved. So we leave the issue open but close the now obsolete PR.   
  
  
  
  
  
  
  

  
  
>

**Comment by nkrah** [comment]
already implemented via other merged PR

**Pull request closed without merging**
