### PR TITLE
Consolidate 

### PR DESCRIPTION
**Pull request by dsarrut**
I adapted tolerances + set seeds + added execution rights to some tests.

@MartiDvrk, @andiresch it seems that the test test059_tpsource_weights.py fails. Can you please check why? 
thanks !

@nkrah unsure to like the default dump for the label_to_mat file. To be discussed

### CODE REVIEW

**Comment by nkrah** [comment]
Sure, we can discuss that. What don't you like about it?

**Comment by dsarrut** [comment]
something wrong here, a lot of tests fail in the mac-os-3.10 while all tests pass with other architectures. 

`KeyError: "Error in the Opengate library (C++): Cannot find the key 'gray' in the list of keys: _name element_type type_name mother filters filters_boolean_operator priority size spacing output translation img_coord_system output_origin uncertainty square physical_volume_index hit_type dose to_water use_more_ram ste_of_mean ste_of_mean_unbiased goal_uncertainty thresh_voxel_edep_for_unc_calc dose_calc_on_the_fly "

**Comment by nkrah** [comment]
Strange. At want point is this error provoked?

**Comment by dsarrut** [comment]
Almost ok, but one test is not working on my computer: test059_tpsource_weights.py
Can you please look at it @MartiDvrk or @andiresch thanks ;) !

**Comment by dsarrut** [comment]
Check : test069_rotation_DICOM_RT_plan_dynamic.py

**Comment by MartiDvrk** [comment]
> > Almost ok, but one test is not working on my computer: test059_tpsource_weights.py Can you please look at it @MartiDvrk or @andiresch thanks ;) !
> 
> as mentioned in the big PR we just closed, for me the test never fails, also after removing the output folder. The only thing that could be different is the plan file. Can you try to use this one? Maybe we changed it at some point and I forgot to update it in the data. If that doesn't solve the issue, I will further investigate. [TreatmentPlan2Spots.txt](https://github.com/OpenGATE/opengate/files/14495748/TreatmentPlan2Spots.txt)

Hello, I don't know if this is solved, but you can check that the rotation axis for the tp source is 'x' and the rotation is 90 deg.

**Comment by dsarrut** [comment]
yes, it is ok now, thanks @MartiDvrk, I just changed the TreatmanPlan2Spots.txt you send ;)

**Pull request merged**
