### PR TITLE
Kill actor interacting particles

### PR DESCRIPTION
**Pull request by majacquet**
Creation of an actor which kill a particle exiting the attached volume if the particle underwent an interaction within the volume

### CODE REVIEW

**Comment by nkrah** [comment]
Please do not merge this into master. I think it will be easier to manually include this into PR #403 or add the functionality manually once the PR #403 is merged into master.

**Comment by nkrah** [comment]
@majacquet : Could you please adapt the KillInteractingParticlesActpr to the new actor style -> see current master. That would be great.

**Comment by majacquet** [comment]
> 

I will open a new branch and proposes a new PR, therefore i will close this one

**Comment by nkrah** [comment]
Ok   
  
  
  
  
  
  
  

  
  
>

**Pull request closed without merging**
