### PR TITLE
Phs source fixed segmentation fault (#328)

### PR DESCRIPTION
**Pull request by tbaudier**
Squash of https://github.com/OpenGATE/opengate/pull/328/files

### CODE REVIEW

**Comment by tbaudier** [comment]
The output of the test is empty @GitFuchs 
```
(venv) (base) tbaudier@eq4-tb-693 opengate_other % python opengate/tests/src/test060_phsp_source_particletype_direct.py
Importing opengate (thread 3177842) ... done
create reference PhS file
Dispatching simulation to subprocess ...
Importing opengate (thread 3177925) ... done
Importing opengate (thread 3178006) ... done
Simulation: create RunManager (single thread)
Simulation: initialize Geometry
Simulation: initialize Physics
Simulation: initialize Source
Simulation: initialize Actors
Simulation: initialize G4RunManager
Simulation: (no volumes overlap checking)
--------------------------------------------------------------------------------
Simulation: START (in a new process)
Simulation: STOP. Run: 1. Time: 1.1 seconds.
--------------------------------------------------------------------------------
Testing PhS source particle name
world
Simulation: create RunManager (single thread)
Simulation: initialize Geometry
Simulation: initialize Physics
Simulation: initialize Source
Simulation: initialize Actors
Simulation: initialize G4RunManager
Simulation: (no volumes overlap checking)
--------------------------------------------------------------------------------
Simulation: START 
End of the phase-space 1 elements, restart from beginning. Cycle count = 1
New event 0
New track e- eid=0
Empty output, no particles stored in /Users/tbaudier/Software/GatePython/opengate_other/opengate/tests/src/../output/test060/test_source_electron.root
Simulation: STOP. Run: 1. Time: 1.1 seconds.
--------------------------------------------------------------------------------
File '/Users/tbaudier/Software/GatePython/opengate_other/opengate/tests/src/../output/test060/test_source_electron.root' does not exist.
```

**Comment by tbaudier** [comment]
Hello Hermann,

Thank you for the bug fix. I integrated inside that PR and rebase everything on master.

Unfortunately, the test test019_linac_elekta_versa_with_mlc_phsp_source.py does not work because inside the phsp used by that test, the PDGCode and Weight keys are not present, they are not necessary for the test. Do you have a solution?

Thank you
Thomas

**Comment by GitFuchs** [comment]
Hi Thomas,

the mentioned tests work again.
The code complained that the PDGCode is not present although it was not needed.
I have fixed it (e.g. added an exception to only complain if something is missing if it is really needed.).

Best,
Hermann

**Comment by tbaudier** [comment]
Hello Hermann,

There is an error with the test: test019_linac_elekta_versa_with_mlc_phsp_source.py . Is it possible for you to have a look please?

Thank you
Thomas

```
(in /Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/sources/phspsources.py line 223)
PhaseSpaceSource: no Weight key (None) in the phsp file.
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/tests/../tests/src/test019_linac_elekta_versa_with_mlc_phsp_source.py", line 171, in <module>
    sim.run()
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/managers.py", line 1461, in run
    self.output = self._run_simulation_engine(False)
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/managers.py", line 1439, in _run_simulation_engine
    output = se.run_engine()
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/engines.py", line 1097, in run_engine
    self.start_and_stop()
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/engines.py", line 1127, in start_and_stop
    self.source_engine.start()
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/engines.py", line 159, in start
    self.g4_master_source_manager.StartMasterThread()
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/sources/phspsources.py", line 223, in generate
    fatal(
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate/exception.py", line 28, in fatal
    raise Exception(s)
Exception: PhaseSpaceSource: no Weight key (None) in the phsp file.
Geant4 data folder does not exist.
I will create it for you here: /Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/opengate_core/geant4_data
... and download the G4 data.
This will take a moment.
```

**Comment by dsarrut** [comment]
By default, there is a weight_key (equal to "Weight"), so the source expect to read this attribute in the phsp while it is not. 
A quick workaround is to set weight_key to None here :https://github.com/OpenGATE/opengate/blob/master/opengate/contrib/linacs/elektaversa.py#L383C5-L383C35

**Comment by tbaudier** [comment]
With https://github.com/OpenGATE/opengate/pull/407/commits/579e86e33ba16fb588cceb3ff7ed4977b71a63bc
Still the error:
https://github.com/OpenGATE/opengate/actions/runs/10090928904/job/27903598411#step:4:552

**Pull request merged**
