### PR TITLE
Multiple fixes and improvements to consolidate the actor refactoring

### PR DESCRIPTION
**Pull request by nkrah**
…roperty

### CODE REVIEW

**Comment by dsarrut** [comment]
Warning: not based on master, unclear how to rebase (a lot of warning remains)

**Comment by nkrah** [comment]
Ah, not good. And strange to be honest. I thought I branched off from master. I'll check and let you know.

**Comment by dsarrut** [comment]
Please consider #464 also (which is merged with this #462)

**Comment by nkrah** [comment]
Ok
  
  
  
  
  
  
  

  
  
>

**Comment by tbaudier** [comment]
Merged with https://github.com/OpenGATE/opengate/pull/464, I close that PR

**Pull request closed without merging**
